# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='languages.Language'),
        ),
        migrations.AddField(
            model_name='job',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='languages.Language'),
            preserve_default=False,
        ),
    ]
