# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20170902_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='job',
            name='language',
            field=models.CharField(choices=[(b'en', 'English'), (b'fr', 'French')], max_length=5),
        ),
    ]
