# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20170908_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='language',
            field=models.CharField(choices=[(b'en', 'English'), (b'fr', 'French')], max_length=5),
        ),
    ]
