# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20170908_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='language',
            new_name='lang',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='end_date',
            new_name='enddate',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='language',
            new_name='lang',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='start_date',
            new_name='startdate',
        ),
        migrations.AlterModelTable(
            name='education',
            table='education',
        ),
        migrations.AlterModelTable(
            name='job',
            table='jobs',
        ),
    ]
